
DataFolder = '/Users/carsten/Dropbox (MIT)/Ephys/EEGcode/DataMark/11-10-2020/';

EEG_SpikeFinder(DataFolder,...
                'ExcludeInitialMinutes',    3,...
                'ExcludeLastMinutes',       1,...
                'startTimeBlockInMinutes',  20,...
                'endTimeBlockInMinutes',    5);