
DataFolder = '/Users/carsten/Dropbox (MIT)/Ephys/EEGcode/sortedData/ins44del1 hom/';

EEG_SpikeFinder(DataFolder,...
                'ExcludeInitialMinutes',    5,...
                'ExcludeLastMinutes',       5,...
                'startTimeBlockInMinutes',  40,...
                'endTimeBlockInMinutes',    10);